# frozen_string_literal: true

namespace :export do
  # The Workers site reads a D1 database; D1 is SQLite, so the export is the
  # app database's own DDL (from sqlite_master) plus batched INSERT
  # statements, written in foreign-key order. Loaded with:
  #   cd site && npx wrangler d1 execute rakkan --local --file=../db/d1_export.sql
  desc "Write db/d1_export.sql for the Workers site's D1 database"
  task :d1 do
    require "hanami/boot"
    require "digest"
    require "json"

    tables = %w[registries packages package_versions adoption_snapshots]
    db = Hanami.app["db.gateway"].connection
    out = Hanami.app.root.join("db", "d1_export.sql")
    metadata_out = Hanami.app.root.join("db", "d1_export.meta.json")
    tmp = "#{out}.tmp"
    metadata_tmp = "#{metadata_out}.tmp"
    batch_size = 200
    counts = {}
    generated_at = nil
    schema_contract = JSON.parse(
      File.read(File.expand_path("../../site/schema-contract.json", __dir__), encoding: "UTF-8")
    )
    schema_version = schema_contract.fetch("version")
    compatible_versions = schema_contract.fetch("compatibleVersions")
    unless schema_version.is_a?(Integer) && schema_version.positive?
      raise ArgumentError, "site schema contract version must be a positive integer"
    end
    unless compatible_versions.is_a?(Array) && !compatible_versions.empty? &&
           compatible_versions.all? { |version| version.is_a?(Integer) && version.positive? } &&
           compatible_versions.uniq == compatible_versions && compatible_versions.include?(schema_version)
      raise ArgumentError,
            "site schema compatible versions must be unique positive integers including the export version"
    end

    # One read transaction keeps SQL and metadata on the same snapshot. The
    # checksum makes every interrupted two-file publication fail closed.
    File.open(tmp, "w") do |f|
      db.transaction do
        f.puts "-- Generated by `rake export:d1`. Tables in foreign-key order."
        f.puts "DROP TABLE IF EXISTS export_meta;"
        tables.reverse_each { |t| f.puts "DROP TABLE IF EXISTS #{t};" }
        tables.each do |table|
          ddl = db[:sqlite_master].where(tbl_name: table).exclude(sql: nil)
                                  .order(Sequel.case({ { type: "table" } => 0 }, 1), :name)
                                  .select_map(:sql)
          ddl.each { |sql| f.puts "#{sql};" }

          columns = db[table.to_sym].columns
          db[table.to_sym].order(:id).each_slice(batch_size) do |rows|
            values = rows.map do |row|
              "(#{columns.map { |c| db.literal(row[c]) }.join(",")})"
            end
            f.puts "INSERT INTO #{table} (#{columns.join(",")}) VALUES #{values.join(",")};"
          end
          counts[table] = db[table.to_sym].count
        end

        # Write the acceptance marker only after every data statement. A
        # failed or interrupted importer must not expose a new generation as
        # complete merely because it reached the first statements.
        generated_at = Time.now.utc.strftime("%Y-%m-%d %H:%M:%S.%6N")
        f.puts "CREATE TABLE export_meta (generated_at timestamp NOT NULL, schema_version integer NOT NULL);"
        f.puts "INSERT INTO export_meta (generated_at, schema_version) " \
               "VALUES (#{db.literal(generated_at)}, #{schema_version});"
      end
    end
    File.write(
      metadata_tmp,
      JSON.pretty_generate(
        version: 1,
        database: "rakkan",
        generated_at: generated_at,
        schema_version: schema_version,
        counts: counts,
        export_sha256: Digest::SHA256.file(tmp).hexdigest
      ) << "\n",
      encoding: "UTF-8"
    )
    File.rename(tmp, out)
    File.rename(metadata_tmp, metadata_out)

    puts "wrote #{out} (#{counts.map { |t, c| "#{t}: #{c}" }.join(", ")})"
  end
end
