# frozen_string_literal: true

namespace :export do
  # The Workers site reads a D1 database; D1 is SQLite, so the export is the
  # app database's own DDL (from sqlite_master) plus batched INSERT
  # statements, written in foreign-key order. Loaded with:
  #   cd site && npx wrangler d1 execute rakkan --local --file=../db/d1_export.sql
  desc "Write db/d1_export.sql for the Workers site's D1 database"
  task :d1 do
    require "hanami/boot"

    tables = %w[registries packages package_versions adoption_snapshots]
    db = Hanami.app["db.gateway"].connection
    out = Hanami.app.root.join("db", "d1_export.sql")
    tmp = "#{out}.tmp"
    batch_size = 200
    counts = {}

    # One read transaction for a consistent snapshot even if ingestion runs
    # concurrently; tmp-then-rename so an interrupted export can never
    # destroy the previous usable file.
    File.open(tmp, "w") do |f|
      db.transaction do
        f.puts "-- Generated by `rake export:d1`. Tables in foreign-key order."
        f.puts "DROP TABLE IF EXISTS export_meta;"
        tables.reverse_each { |t| f.puts "DROP TABLE IF EXISTS #{t};" }
        # The site's freshness stamp: when this dataset was built. In the
        # deploy pipeline the export runs only after ingest succeeds, so
        # this is also "the pipeline last completed here".
        f.puts "CREATE TABLE export_meta (generated_at timestamp NOT NULL);"
        f.puts "INSERT INTO export_meta (generated_at) VALUES (#{db.literal(Time.now.utc)});"

        tables.each do |table|
          ddl = db[:sqlite_master].where(tbl_name: table).exclude(sql: nil)
                                  .order(Sequel.case({ { type: "table" } => 0 }, 1), :name)
                                  .select_map(:sql)
          ddl.each { |sql| f.puts "#{sql};" }

          columns = db[table.to_sym].columns
          db[table.to_sym].order(:id).each_slice(batch_size) do |rows|
            values = rows.map do |row|
              "(#{columns.map { |c| db.literal(row[c]) }.join(",")})"
            end
            f.puts "INSERT INTO #{table} (#{columns.join(",")}) VALUES #{values.join(",")};"
          end
          counts[table] = db[table.to_sym].count
        end
      end
    end
    File.rename(tmp, out)

    puts "wrote #{out} (#{counts.map { |t, c| "#{t}: #{c}" }.join(", ")})"
  end
end
